CREATE TABLE IF NOT EXISTS TRANSACTIONS (

    ID BIGINT PRIMARY KEY AUTO_INCREMENT,
    STEP INTEGER NOT NULL,
    TYPE ENUM('CASH_IN', 'CASH_OUT', 'DEBIT', 'PAYMENT', 'TRANSFER') NOT NULL,
    AMOUNT DECIMAL(15, 2) NOT NULL,
    NAME_ORIGIN VARCHAR(50) NOT NULL,
    OLD_BALANCE_ORIGIN DECIMAL(15, 2) NOT NULL,
    NEW_BALANCE_ORIGIN DECIMAL(15, 2) NOT NULL,
    NAME_RECIPIENT VARCHAR(50) NOT NULL,
    OLD_BALANCE_RECIPIENT DECIMAL(15, 2) NOT NULL,
    NEW_BALANCE_RECIPIENT DECIMAL(15, 2) NOT NULL,
    ISFRAUD BOOLEAN NOT NULL,
    ISFLAGGEDFRAUD BOOLEAN NOT NULL,

);
