CREATE TABLE IF NOT EXISTS TRANSACTION_CUSTOMERS (

    ID BIGINT PRIMARY KEY AUTO_INCREMENT,
    NAME VARCHAR(100) NOT NULL,
    OLD_BALANCE DECIMAL(15, 2) NOT NULL,
    NEW_BALANCE DECIMAL(15, 2) NOT NULL

);

CREATE TABLE IF NOT EXISTS TRANSACTIONS (

    ID BIGINT PRIMARY KEY AUTO_INCREMENT,
    STEP INTEGER NOT NULL,
    TYPE ENUM('CASH_IN', 'CASH_OUT', 'DEBIT', 'PAYMENT', 'TRANSFER') NOT NULL,
    AMOUNT DECIMAL(15, 2) NOT NULL,
    ORIGIN_ID BIGINT NOT NULL,
    RECIPIENT_ID BIGINT NOT NULL,
    ISFRAUD BOOLEAN NOT NULL,
    ISFLAGGEDFRAUD BOOLEAN NOT NULL,
    CONSTRAINT FK_ORIGIN FOREIGN KEY (ORIGIN_ID) REFERENCES TRANSACTION_CUSTOMERS(ID),
    CONSTRAINT FK_RECIPIENT FOREIGN KEY (RECIPIENT_ID) REFERENCES TRANSACTION_CUSTOMERS(ID)

);
